language: ruby
rvm:
  - 2.4.0
sudo: false
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:schema:load
  - RAILS_ENV=test bundle exec rake db:seed
  - RAILS_ENV=test bundle exec rake db:test:prepare
  - RAILS_ENV=test bundle exec rake test
  - RAILS_ENV=test bundle exec rake spec
before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test' -U postgres
notifications:
  slack:
    secure: DE7RFYp6wElEvl1MtxhtmLJlgvMhLQeRnIuLOn+BGli6xtzqO8wGO5N3gkq/CrLQTN0wKUJbuZwtxX3m30248sromR3A2R0KeJ5KkoDqTCubmkPT0aEsz6HlCkQPdnOe5bBvGXsHFKvEuPCXc+FRQugDMPk+AGRcACoS9faCmsE=
