development:
  year: 2017
  max_users_limit: 2000
  tutorial_registration_open: true
  lightning_registration_open: true
  program_released: true
  speakers_released: true
  early_bird_ends: 2017-02-07 23:59:59 +1
  sponsor_price_in_nok_before_vat: 28000

test:
  year: 2017
  max_users_limit: 2000
  tutorial_registration_open: false
  lightning_registration_open: false
  program_released: false
  early_bird_ends: 2017-02-07 23:59:59 +1
  sponsor_price_in_nok_before_vat: 28000

staging:
  year: 2017
  max_users_limit: 2000
  tutorial_registration_open: true
  lightning_registration_open: true
  program_released: false
  speakers_released: false
  early_bird_ends: 2017-02-07 23:59:59 +1
  sponsor_price_in_nok_before_vat: 28000

production:
  year: 2017
  max_users_limit: 300
  tutorial_registration_open: true
  lightning_registration_open: true
  program_released: false
  speakers_released: false
  early_bird_ends: 2017-02-07 23:59:59 +1
  sponsor_price_in_nok_before_vat: 28000
