development:
  year: 2020
  cfp_open: true
  proposals_visible: true
  program_released: true
  speakers_released: false
  early_bird_ends: 2020-02-13 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 29000
  fiken_email: "anders.rorvik@gmail.com"
  fiken_invoice_bank_account_href: https://fiken.no/api/v1/companies/fiken-demo-venstre-og-fysisk-rakett-as/bank-accounts/756577080
  fiken_stripe_account_code: "1960:10001"
  stripe_on: true
  ticket_sales_open: true

test:
  year: 2020
  proposals_visible: false
  program_released: false
  early_bird_ends: 2020-02-13 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 29000
  fiken_email: "anders.rorvik@gmail.com"
  fiken_invoice_bank_account_href: https://fiken.no/api/v1/companies/fiken-demo-venstre-og-fysisk-rakett-as/bank-accounts/756577080
  fiken_stripe_account_code: "1960:10001"
  stripe_on: true
  ticket_sales_open: false

staging:
  year: 2020
  cfp_open: false
  proposals_visible: false
  program_released: true
  speakers_released: true
  early_bird_ends: 2020-02-13 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 31000
  fiken_email: "anders.rorvik@gmail.com"
  fiken_invoice_bank_account_href: https://fiken.no/api/v1/companies/fiken-demo-venstre-og-fysisk-rakett-as/bank-accounts/756577080
  fiken_stripe_account_code: "1960:10001"
  stripe_on: true
  ticket_sales_open: true

production:
  year: 2020
  cfp_open: false
  proposals_visible: false
  program_released: true
  speakers_released: true
  early_bird_ends: 2020-02-16 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 31000
  fiken_email: "foreningen-boosterkonferansen@bilag.fiken.no"
  fiken_invoice_bank_account_href: https://fiken.no/api/v1/companies/foreningen-boosterkonferansen/bank-accounts/253144070
  fiken_stripe_account_code: "1960:10001"
  stripe_on: true
  ticket_sales_open: true
