development:
  year: 2018
  cfp_open: true
  proposals_visible: true
  program_released: false
  speakers_released: false
  early_bird_ends: 2018-02-07 23:59:59 +1
  partner_price_in_nok_before_vat: 29000
  fiken_email: "anders.rorvik@gmail.com"
  stripe_on: true

test:
  year: 2018
  proposals_visible: true
  program_released: false
  early_bird_ends: 2018-02-07 23:59:59 +1
  partner_price_in_nok_before_vat: 29000
  fiken_email: "anders.rorvik@gmail.com"
  stripe_on: true

staging:
  year: 2018
  cfp_open: true
  proposals_visible: false
  program_released: false
  speakers_released: false
  early_bird_ends: 2018-02-14 23:59:59 +1
  partner_price_in_nok_before_vat: 31000
  fiken_email: "anders.rorvik@gmail.com"
  stripe_on: true

production:
  year: 2018
  cfp_open: true
  proposals_visible: false
  program_released: false
  speakers_released: false
  early_bird_ends: 2018-02-14 23:59:59 +1
  partner_price_in_nok_before_vat: 31000
  fiken_email: "foreningen-boosterkonferansen@bilag.fiken.no"
  stripe_on: true
