development:
  year: 2019
  cfp_open: true
  proposals_visible: true
  program_released: false
  speakers_released: false
  early_bird_ends: 2019-02-13 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 29000
  fiken_email: "anders.rorvik@gmail.com"
  stripe_on: true
  ticket_sales_open: false

test:
  year: 2019
  proposals_visible: false
  program_released: false
  early_bird_ends: 2019-02-13 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 29000
  fiken_email: "anders.rorvik@gmail.com"
  stripe_on: true
  ticket_sales_open: true

staging:
  year: 2019
  cfp_open: true
  proposals_visible: true
  program_released: true
  speakers_released: false
  early_bird_ends: 2019-02-13 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 31000
  fiken_email: "anders.rorvik@gmail.com"
  stripe_on: true
  ticket_sales_open: true

production:
  year: 2019
  cfp_open: false
  proposals_visible: false
  program_released: true
  speakers_released: false
  early_bird_ends: 2019-02-13 23:59:59 +1
  early_bird_ticket_limit: 100
  partner_price_in_nok_before_vat: 31000
  fiken_email: "foreningen-boosterkonferansen@bilag.fiken.no"
  stripe_on: true
  ticket_sales_open: true 
