s3: &s3
  storage: s3
  s3_credentials: <%= Rails.root %>/config/s3.yml
  path: ":attachment/:id/:basename_:style.:extension"
  url: ":s3_domain_url"
  s3_protocol: "https"
  s3_region: 'eu-west-1'

test:
  storage: filesystem

development:
  <<: *s3

staging:
  <<: *s3

production:
  <<: *s3