free_prices: &free_prices
  speaker: 0
  organizer: 0
  volunteer: 0
  sponsor: 0

prices: &prices
  early_bird: 5500
  full_price: 7000
  one_day: 3500
  lightning: 3500
  reviewer: 4400
  dinner: 0
  <<: *free_prices

development: &development
  prices:
    early_bird: 10
    full_price: 12
    one_day: 5
    lightning: 5
    reviewer: 5
    <<: *free_prices
  paypal_email: paypal_1297107898_biz@rootsconf.no
  paypal_url: "https://www.sandbox.paypal.com/cgi-bin/webscr"
  send_regning_url: "https://kontakt%40rootsconf.no:jySGOHz7@www.sendregning.no/ws/butler.do?action=send&type=invoice&test=true"

staging:
  prices:
    early_bird: 10
    full_price: 12
    one_day: 5
    lightning: 5
    reviewer: 5
    <<: *free_prices
  paypal_email: paypal_1297107898_biz@rootsconf.no
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"
  send_regning_url: "https://www.sendregning.no/ws/butler.do?action=send&type=invoice&test=true"

test:
  prices:
    early_bird: 10
    full_price: 12
    one_day: 5
    lightning: 5
    reviewer: 5
    <<: *free_prices
  paypal_email: paypal_1297107898_biz@rootsconf.no
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"
  send_regning_url: "https://www.sendregning.no/ws/butler.do?action=send&type=invoice&test=true"

production: &production
  prices:
    <<: *prices
  paypal_email: paypal@rootsconf.no
  paypal_url: "https://www.paypal.com/cgi-bin/webscr"
  send_regning_url: "https://kontakt%40rootsconf.no:jySGOHz7@www.sendregning.no/ws/butler.do?action=send&type=invoice"