# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 852f7e82079de806fa10eb7e8168ec73e959c830e818f214b1a77a31ac6b354f294f030b595d2f5ad966ed246b1403efcc98028fca7d83208763a5df91c7ca73

test:
  secret_key_base: ad820ed062871e53bf94d0320a5363a3d7356f342df7e3fb4f159c2cd90ba9828edd8f79e8b4af318d33212dc4a38e2e249306cec140bd6e215dc21a91e55a1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
